version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: hiringjet_admin
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "9105:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hiringjet_db
      POSTGRES_USER: hiringjet_user
      POSTGRES_PASSWORD: hiringjet_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: